<?php

include "FaceDetector.php";

$detector = new FaceDetector('detection.dat');
$detector->faceDetect('lena512color.jpg');
$detector->toJpeg();
?>

<!DOCTYPE html>
<html>
<body>

<form action="FaceDetector.php" method="post" enctype="multipart/form-data">
    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">
</form>

</body>
</html>